### ISSUE TITLE
GitHub Sponsors

### ISSUE THREAD

**Issue by Snuggle** [C1710/blobmoji#112]
Hey! 

This is my favourite emoji set and I would love to support its continuation. Could I please ask for GitHub Sponsors to be added so that we are able to donate towards the continued maintenance & upkeep of blobmoji's?

Thanks!

**Comment by C1710** [comment]
I don't think that will happen anytime soon 😅

1. This is a hobby project for me. Accepting donations would add some kind of obligation and I don't think I want that (esp. in the next few months I'm not sure how much time I'll be able to spare because I'll have to write my Master Thesis soon)
2. I have no idea if/how I would have to handle taxation, etc.

**Comment by igalic** [comment]
i can only say something about 2.: unless you're getting excessive amounts of donations, it's probably not going to amount to taxable income.

in many countries in Europe, that's around 10k€/year for income tax, and could be as high as 50k€/year for VAT

so: unless (donations + your current income) push you into a different tax category, i wouldn't worry about it.
