### ISSUE TITLE
Water gun

### ISSUE THREAD

**Issue by Madis0** [C1710/blobmoji#14]
[:apple: :gun: :sweat_drops: (click)](https://blog.emojipedia.org/google-updates-gun-emoji/)

I would suggest a green, extra balloon-less one for consistency.

**Comment by C1710** [comment]
Oh - another probalby very stupid solution would be to make it an emoji sequence - without the ZWJ.  
The one huge problem would be that you couldn't see 💦 🔫 (or the other way round) as two emojis but only as one emoji. And it wouldn't change anything on the issue of receiving messages of people using other fonts.

**Comment by Madis0** [comment]
That water gun looks nice.

Not sure how much confusion it would make, but you could provide two versions with real gun being the default _now_ and water gun being the default when P gets released. That would be consistent with Google's intentions.

Perhaps make the real one a combination of :gun: :bomb:? Although that could again be misinterpreted as a *water* bomb, if it is near a water gun :grin: 

> what's the plural of OS?

I believe it is "OSes" :grinning:

**Comment by Madis0** [comment]
Theoretical other combinations, though they don't make much sense:
* 🔫⚔️
* 🔫🏹
* 🔫🔪
* 🔫🗡️

**Comment by C1710** [comment]
This is what I meant with "making the toy gun the default".  
But I'd opt for 💣🔫 because the bomb would then represent the bullet.  
I'm not very sure about this issue but I'll probably offer both versions.  
I mean, if you get this font into your OS, you're able to use the other version as well.  
And regarding EmojiCompat: I released a new File based configuration for this which makes it possible to exchange the emoji font without having to wait for the app developer to do so.  
I guess, this will also be one of the options in [Tusky](https://github.com/tuskyapp/Tusky).

**Comment by Jop-V** [comment]
Here's an idea... A gun and a water pistol have roughly the same sillioutte, so you could display an outline/sillioutte by default, and then show a gun for the 🔫💀 (or 🔫💣) ZWJ sequence, and a water pistol for the 🔫💦 ZWJ sequence.

**Comment by C1710** [comment]
I don't actually like this outline solution. In the end this is also supposed to be an emoji font that looks nice.  
A blank silhouette wouldn't look very nice I think.

**Comment by Jop-V** [comment]
It's still preferable to this... 😟

![Emojipedia's example](https://blog.emojipedia.org/content/images/2016/08/emojipedia-pistol-emoji-cross-platform.png)
_(From https://blog.emojipedia.org/apple-and-the-gun-emoji/)_

**Comment by C1710** [comment]
I'm totally aware of all this problem.  
I'll see what I can do...

**Comment by C1710** [comment]
![regular gun](https://github.com/C1710/blobmoji/raw/master/png/128/emoji_u1f52b.png) ![hybrid](https://user-images.githubusercontent.com/10349490/39266958-bdaba034-48cb-11e8-9d3c-d24c35cb0ad4.png) ![water pistol](https://github.com/C1710/blobmoji/raw/master/png/128/emoji_u1f52b_200d_2063_fe0f.png)

**Comment by C1710** [comment]
I made a new branch including the new hybrid gun 43616539454a66b5430bd85454654f045487f53a

**Comment by Jop-V** [comment]
Wow, I actually like that design! It really can be interpreted as either. I'm impressed!

**Comment by C1710** [comment]
So I guess, I'll close this issue now...

**Comment by April93** [comment]
Just wanted to say, the proper solution is to properly display the character as a legitimate and real firearm, and leave squirtgun as either it's own codepoint, or as an unofficial ZWJ that not everyone supports.

**Comment by C1710** [comment]
And that's the problem: Some prefer the water gun because it's more consistent to the major emoji vendors (now including @Microsoft) and some prefer to stick to the Unicode standard.  
I know that this hybrid version is _not_ a perfect solution, but I think it's the best solution currently possible.  
This ZWJ solution is of course very nice in theory and it's the one I originally used, but there's one problem: IME.  
Even if the user knows that there's a custom ZWJ sequence for the water pistol (`1F52B 200D 2063 FE0F`), they can't type it using their regular Android or Windows* device as they don't have a native Unicode codepoint input.  

*Actually Windows _has_ Unicode codepoint input, but you can't use it without a numpad.

**Comment by C1710** [comment]
And BTW I still think the most "perfect" solution would be to have two codepoints in the Unicode standard.  
But even this one would cause problems as there would be many devices remaining without these additional codepoints which would still cause the same problems as we have now.
