### ISSUE TITLE
Official blobs as emoji

### ISSUE THREAD

**Issue by Madis0** [C1710/blobmoji#63]
Google has released new blob emoji as stickers, could remake them (or somehow obtain) as emoji instead. https://www.androidpolice.com/2021/06/15/gboards-amazing-emoji-kitchen-will-soon-show-the-perfect-emoji-mashup-at-the-perfect-time/

**Comment by C1710** [comment]
I know, but I don't think these could be used:
1. They're not emojis, but mashup stickers, so the overlap will be quite small
2. If there is a way to extract them, it will be most likely not in SVG format
3. Gboard is proprietary software, so even if they could be extracted in a way that works, it would cause legal issues
4. It's actually not the Blobs that are that difficult to make, but all the other emojis, especially when it involves skintones and genders (in that case, simply copying the Noto ones doesn't work due to the changed art style)
