### ISSUE TITLE
unable to install font on macOS

### ISSUE THREAD

**Issue by igalic** [C1710/blobmoji#94]
When installing the [current Beta](https://github.com/C1710/blobmoji/releases/download/v14.0/Blobmoji.ttf) on macOS 11, I get the following error:

> 1 serious error was found. Do not use this font file.

The error is:

> 'sfnt' required tables

after accepting such a fate, and proceeding with the installation, the font cannot be found.

I have tried the other .ttfs:

- BlobmojiWindows.ttf installs as Segoe UI, but none of the characters in the preview look sensible in any way.
- The BlobmojiCompat.ttf gives the same error was Blobmoji.ttf

**Comment by C1710** [comment]
macOS does not support this kind of color font at all.  
The only difference between the standard and Windows 10-compatible font is that there's an additional dummy table present, but in the end it's still a CBDT/CBLC font which Apple does not support.

I'm not sure if that's the issue here, but trying to install the font on macOS is pointless at the moment and I don't plan to support Apple's SBIX format.

**Comment by igalic** [comment]
Aye, thanks for the info!
